
services:

  chromadb:
    #image: chromadb/chroma
    image: chromadb/chroma:0.6.1
    container_name: chromadb
    volumes:
      - ./volumes/chromadb/data:/chromadb/data
    ports:
      - "8000:8000"
    environment:
      - PERSIST_DIRECTORY=/chromadb/data

  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ./volumes/ollama:/root/.ollama
    ports:
      - "11434:11434"

  app:
    build:
      context: .
      dockerfile: ./Dockerfile.app
    container_name: app
    ports:
      - "8501:8501"
    depends_on:
      - chromadb
      - ollama
    environment:
      - MYRAG_OLLAMA_URL=http://ollama:11434
      - MYRAG_CHROMADB_HOST=chromadb
      - MYRAG_CHROMADB_PORT=8000
